### PR TITLE
feat($monorepo): coalesce duplicate dep updates w/ multiple package.json

### LINKED ISSUE #43: Feature Request: Monorepo New Dependency in multiple packages should only have 1 info section
When you add a dependency to multiple packages, danger-plugin-yarn reports about it multiple-times

TriplicateDeps

Suggested feature: report only once per dependency, but if there are duplicates then add the path to the package.json it was added to.

I totally don't mind providing a PR to do this, but first I wanted to check:
- if you want this feature?
- where in the the message would you want this to live / what wording would make sense?

eg. `<package-name> was added to 3 package.json files: 'apps/app1/package.json', 'apps/app2/package.json', libs/lib1/package.json'`

### PR DESCRIPTION
**Pull request by fbartho**
In a monorepo, you may add a single dependency to multiple package.json files in the repo in a single PR.

This PR changes the display of info, such that there's only 1 entry per dependency, with a list of package.json files to which it applies.

Fixes: #43 

## Example

An entry for a newly discovered package will look like this:
<table>
<tr><td> <h2><a href="https://github.com/danger/danger-js#readme">my-new-dependency</a></h2> </td><td> <i>Used in <code>package.json</code>, <code>packages/my-other-package/package.json</code><i> </td></tr>
<tr><td> <b>Author:</b> <wbr/>Orta Therox </td><td> <b>Description:</b> <wbr/>Unit tests for Team Culture </td></tr>
<tr><td> <b>License:</b> <wbr/>MIT </td><td> <b>Homepage:</b> <wbr/><a href="https://github.com/danger/danger-js#readme">https://<wbr/>github.com/<wbr/>danger/<wbr/>danger-js#readme</a> </td></tr>
<tr><td colspan="2"> <b>Keywords:</b> <wbr/>danger,ci </td></tr>
<tr><td> <b>Updated:</b> <wbr/>over 4 years ago </td><td> <b>Created:</b> <wbr/>over 5 years ago </td></tr>
<tr><td> <b>Releases:</b> <wbr/>45 </td><td> <b>Maintainers:</b> <wbr/>3 </td></tr>
<tr><td colspan="3"> <b>Direct <wbr/>Dependencies:</b> <wbr/><a href='https://www.npmjs.com/package/babel-polyfill'><code>babel-polyfill</code></a>, <wbr/><a href='https://www.npmjs.com/package/chalk'><code>chalk</code></a>, <wbr/><a href='https://www.npmjs.com/package/commander'><code>commander</code></a>, <wbr/><a href='https://www.npmjs.com/package/debug'><code>debug</code></a>, <wbr/><a href='https://www.npmjs.com/package/github'><code>github</code></a>, <wbr/><a href='https://www.npmjs.com/package/jest-config'><code>jest-config</code></a>, <wbr/><a href='https://www.npmjs.com/package/jest-environment-node'><code>jest-environment-node</code></a>, <wbr/><a href='https://www.npmjs.com/package/jest-runtime'><code>jest-runtime</code></a>, <wbr/><a href='https://www.npmjs.com/package/jsome'><code>jsome</code></a>, <wbr/><a href='https://www.npmjs.com/package/jsonpointer'><code>jsonpointer</code></a>, <wbr/><a href='https://www.npmjs.com/package/lodash.find'><code>lodash.find</code></a>, <wbr/><a href='https://www.npmjs.com/package/lodash.includes'><code>lodash.includes</code></a>, <wbr/><a href='https://www.npmjs.com/package/lodash.isobject'><code>lodash.isobject</code></a>, <wbr/><a href='https://www.npmjs.com/package/lodash.keys'><code>lodash.keys</code></a>, <wbr/><a href='https://www.npmjs.com/package/node-fetch'><code>node-fetch</code></a>, <wbr/><a href='https://www.npmjs.com/package/parse-diff'><code>parse-diff</code></a>, <wbr/><a href='https://www.npmjs.com/package/rfc6902'><code>rfc6902</code></a>, <wbr/><a href='https://www.npmjs.com/package/voca'><code>voca</code></a>, <wbr/><a href='https://www.npmjs.com/package/dtslint'><code>dtslint</code></a> </td></tr>
</table>

<details>
<summary><code>README</code></summary></br>

`[...snipped...]`

</details>

### CODE REVIEW

**Comment by fbartho** [comment]
Whoops! I had tagged the wrong issue number. Please see discussion in #43

**Comment by fbartho** [comment]
Now ready for review @orta! Thanks!

**Review by orta — APPROVED** [review]
Yep, code looks great and the README feels good 👍🏻

**Comment by orta** [comment]
Nice, shipped as 1.4.0

**Pull request merged**
